/*
 * jiaozifs API
 *
 * jiaozifs HTTP API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct BlockStoreConfigLocal {
    #[serde(rename = "path")]
    pub path: String,
}

impl BlockStoreConfigLocal {
    pub fn new(path: String) -> BlockStoreConfigLocal {
        BlockStoreConfigLocal {
            path,
        }
    }
}

