/*
 * jiaozifs API
 *
 * jiaozifs HTTP API
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct BlockStoreConfigAzure {
    #[serde(rename = "storage_access_key")]
    pub storage_access_key: String,
    #[serde(rename = "storage_account")]
    pub storage_account: String,
    #[serde(rename = "try_timeout")]
    pub try_timeout: i64,
}

impl BlockStoreConfigAzure {
    pub fn new(
        storage_access_key: String,
        storage_account: String,
        try_timeout: i64,
    ) -> BlockStoreConfigAzure {
        BlockStoreConfigAzure {
            storage_access_key,
            storage_account,
            try_timeout,
        }
    }
}
