/*
 * jiaozifs API
 *
 * jiaozifs HTTP API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Branch {
    #[serde(rename = "id")]
    pub id: uuid::Uuid,
    #[serde(rename = "repository_id")]
    pub repository_id: uuid::Uuid,
    #[serde(rename = "commit_hash")]
    pub commit_hash: String,
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    #[serde(rename = "creator_id")]
    pub creator_id: uuid::Uuid,
    #[serde(rename = "created_at")]
    pub created_at: i64,
    #[serde(rename = "updated_at")]
    pub updated_at: i64,
}

impl Branch {
    pub fn new(id: uuid::Uuid, repository_id: uuid::Uuid, commit_hash: String, name: String, creator_id: uuid::Uuid, created_at: i64, updated_at: i64) -> Branch {
        Branch {
            id,
            repository_id,
            commit_hash,
            name,
            description: None,
            creator_id,
            created_at,
            updated_at,
        }
    }
}

