/*
 * jiaozifs API
 *
 * jiaozifs HTTP API
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct BranchCreation {
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "source")]
    pub source: String,
}

impl BranchCreation {
    pub fn new(name: String, source: String) -> BranchCreation {
        BranchCreation { name, source }
    }
}
