/*
 * jiaozifs API
 *
 * jiaozifs HTTP API
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ChangePair {
    #[serde(rename = "path")]
    pub path: String,
    #[serde(rename = "left", skip_serializing_if = "Option::is_none")]
    pub left: Option<Box<models::Change>>,
    #[serde(rename = "right", skip_serializing_if = "Option::is_none")]
    pub right: Option<Box<models::Change>>,
    #[serde(rename = "is_conflict")]
    pub is_conflict: bool,
}

impl ChangePair {
    pub fn new(path: String, is_conflict: bool) -> ChangePair {
        ChangePair {
            path,
            left: None,
            right: None,
            is_conflict,
        }
    }
}
