/*
 * jiaozifs API
 *
 * jiaozifs HTTP API
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CreateRepository {
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "visible", skip_serializing_if = "Option::is_none")]
    pub visible: Option<bool>,
    /// block storage config url encoded json
    #[serde(rename = "blockstore_config", skip_serializing_if = "Option::is_none")]
    pub blockstore_config: Option<String>,
}

impl CreateRepository {
    pub fn new(name: String) -> CreateRepository {
        CreateRepository {
            description: None,
            name,
            visible: None,
            blockstore_config: None,
        }
    }
}
