/*
 * jiaozifs API
 *
 * jiaozifs HTTP API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct FullTreeEntry {
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "hash")]
    pub hash: String,
    #[serde(rename = "is_dir")]
    pub is_dir: bool,
    #[serde(rename = "size")]
    pub size: i64,
    #[serde(rename = "created_at")]
    pub created_at: i64,
    #[serde(rename = "updated_at")]
    pub updated_at: i64,
}

impl FullTreeEntry {
    pub fn new(name: String, hash: String, is_dir: bool, size: i64, created_at: i64, updated_at: i64) -> FullTreeEntry {
        FullTreeEntry {
            name,
            hash,
            is_dir,
            size,
            created_at,
            updated_at,
        }
    }
}

