/*
 * jiaozifs API
 *
 * jiaozifs HTTP API
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Group {
    #[serde(rename = "id")]
    pub id: uuid::Uuid,
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "policies")]
    pub policies: Vec<uuid::Uuid>,
    #[serde(rename = "created_at")]
    pub created_at: i64,
    #[serde(rename = "updated_at")]
    pub updated_at: i64,
}

impl Group {
    pub fn new(
        id: uuid::Uuid,
        name: String,
        policies: Vec<uuid::Uuid>,
        created_at: i64,
        updated_at: i64,
    ) -> Group {
        Group {
            id,
            name,
            policies,
            created_at,
            updated_at,
        }
    }
}
