/*
 * jiaozifs API
 *
 * jiaozifs HTTP API
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Member {
    #[serde(rename = "id")]
    pub id: uuid::Uuid,
    #[serde(rename = "user_id")]
    pub user_id: uuid::Uuid,
    #[serde(rename = "repo_id")]
    pub repo_id: uuid::Uuid,
    #[serde(rename = "group_id")]
    pub group_id: uuid::Uuid,
    #[serde(rename = "created_at")]
    pub created_at: i64,
    #[serde(rename = "updated_at")]
    pub updated_at: i64,
}

impl Member {
    pub fn new(
        id: uuid::Uuid,
        user_id: uuid::Uuid,
        repo_id: uuid::Uuid,
        group_id: uuid::Uuid,
        created_at: i64,
        updated_at: i64,
    ) -> Member {
        Member {
            id,
            user_id,
            repo_id,
            group_id,
            created_at,
            updated_at,
        }
    }
}
