/*
 * jiaozifs API
 *
 * jiaozifs HTTP API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct MergeMergeRequest {
    #[serde(rename = "msg")]
    pub msg: String,
    /// use to record the resolution of the conflict, example({\"b/a.txt\":\"left\"})
    #[serde(rename = "conflict_resolve", skip_serializing_if = "Option::is_none")]
    pub conflict_resolve: Option<std::collections::HashMap<String, String>>,
}

impl MergeMergeRequest {
    pub fn new(msg: String) -> MergeMergeRequest {
        MergeMergeRequest {
            msg,
            conflict_resolve: None,
        }
    }
}

