/*
 * jiaozifs API
 *
 * jiaozifs HTTP API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Tag {
    #[serde(rename = "id")]
    pub id: uuid::Uuid,
    #[serde(rename = "repository_id")]
    pub repository_id: uuid::Uuid,
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "creator_id")]
    pub creator_id: uuid::Uuid,
    #[serde(rename = "target")]
    pub target: String,
    #[serde(rename = "message", skip_serializing_if = "Option::is_none")]
    pub message: Option<String>,
    #[serde(rename = "created_at")]
    pub created_at: i64,
    #[serde(rename = "updated_at")]
    pub updated_at: i64,
}

impl Tag {
    pub fn new(id: uuid::Uuid, repository_id: uuid::Uuid, name: String, creator_id: uuid::Uuid, target: String, created_at: i64, updated_at: i64) -> Tag {
        Tag {
            id,
            repository_id,
            name,
            creator_id,
            target,
            message: None,
            created_at,
            updated_at,
        }
    }
}

