/*
 * jiaozifs API
 *
 * jiaozifs HTTP API
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct TreeEntry {
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "hash")]
    pub hash: String,
    #[serde(rename = "is_dir")]
    pub is_dir: bool,
}

impl TreeEntry {
    pub fn new(name: String, hash: String, is_dir: bool) -> TreeEntry {
        TreeEntry { name, hash, is_dir }
    }
}
